{% set name = "pyrms" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrms-{{ version }}.tar.gz
  sha256: a9081032b39687370fc475f3fc9e8e32deb85ab5e0c9ecfa727ef5f6ad174a5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyrms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python wrapper for the ReactionMechanismSimulator
  home: https://github.com/ReactionMechanismGenerator/pyrms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
